# Generated by Django 3.2.7 on 2021-09-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20210905_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
